language: csharp
solution: BetBuddy/BetBud.sln
branches:
  only:
    - master
    - dev
script:
  - xbuild /p:Configuration=Release BetBuddy/BetBud.sln /p:TargetFrameworkVersion="v4.5"
  - mono ./testrunner/NUnit.ConsoleRunner.3.2.0/tools/nunit3-console.exe ./BetBud/BetBudTest/bin/Release/BetBuddyTest.dll
notifications:
  email: false
install:
  - nuget restore BetBuddy/BetBud.sln
  - nuget install NUnit.Runners -Version 3.2.0 -OutputDirectory testrunner
