//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SæsonBeskrivelse", Namespace="http://schemas.datacontract.org/2004/07/ModelLibrary.SeasonInterface")]
    [System.SerializableAttribute()]
    public partial class SæsonBeskrivelse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BeskrivelseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SlutDatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartDatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SæsonBeskrivelseIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Beskrivelse {
            get {
                return this.BeskrivelseField;
            }
            set {
                if ((object.ReferenceEquals(this.BeskrivelseField, value) != true)) {
                    this.BeskrivelseField = value;
                    this.RaisePropertyChanged("Beskrivelse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SlutDato {
            get {
                return this.SlutDatoField;
            }
            set {
                if ((object.ReferenceEquals(this.SlutDatoField, value) != true)) {
                    this.SlutDatoField = value;
                    this.RaisePropertyChanged("SlutDato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartDato {
            get {
                return this.StartDatoField;
            }
            set {
                if ((object.ReferenceEquals(this.StartDatoField, value) != true)) {
                    this.StartDatoField = value;
                    this.RaisePropertyChanged("StartDato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SæsonBeskrivelseId {
            get {
                return this.SæsonBeskrivelseIdField;
            }
            set {
                if ((this.SæsonBeskrivelseIdField.Equals(value) != true)) {
                    this.SæsonBeskrivelseIdField = value;
                    this.RaisePropertyChanged("SæsonBeskrivelseId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kupon", Namespace="http://schemas.datacontract.org/2004/07/ModelLibrary.Kupon")]
    [System.SerializableAttribute()]
    public partial class Kupon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminPanel.ServiceReference1.Bruger BrugerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BrugerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool KontrolleretField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KuponIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SæsonIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminPanel.ServiceReference1.DelKamp[] delKampeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdminPanel.ServiceReference1.Bruger Bruger {
            get {
                return this.BrugerField;
            }
            set {
                if ((object.ReferenceEquals(this.BrugerField, value) != true)) {
                    this.BrugerField = value;
                    this.RaisePropertyChanged("Bruger");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BrugerId {
            get {
                return this.BrugerIdField;
            }
            set {
                if ((this.BrugerIdField.Equals(value) != true)) {
                    this.BrugerIdField = value;
                    this.RaisePropertyChanged("BrugerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDateTime {
            get {
                return this.CreateDateTimeField;
            }
            set {
                if ((this.CreateDateTimeField.Equals(value) != true)) {
                    this.CreateDateTimeField = value;
                    this.RaisePropertyChanged("CreateDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kontrolleret {
            get {
                return this.KontrolleretField;
            }
            set {
                if ((this.KontrolleretField.Equals(value) != true)) {
                    this.KontrolleretField = value;
                    this.RaisePropertyChanged("Kontrolleret");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KuponId {
            get {
                return this.KuponIdField;
            }
            set {
                if ((this.KuponIdField.Equals(value) != true)) {
                    this.KuponIdField = value;
                    this.RaisePropertyChanged("KuponId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Point {
            get {
                return this.PointField;
            }
            set {
                if ((this.PointField.Equals(value) != true)) {
                    this.PointField = value;
                    this.RaisePropertyChanged("Point");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SæsonId {
            get {
                return this.SæsonIdField;
            }
            set {
                if ((this.SæsonIdField.Equals(value) != true)) {
                    this.SæsonIdField = value;
                    this.RaisePropertyChanged("SæsonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdminPanel.ServiceReference1.DelKamp[] delKampe {
            get {
                return this.delKampeField;
            }
            set {
                if ((object.ReferenceEquals(this.delKampeField, value) != true)) {
                    this.delKampeField = value;
                    this.RaisePropertyChanged("delKampe");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bruger", Namespace="http://schemas.datacontract.org/2004/07/ModelLibrary.Bruger")]
    [System.SerializableAttribute()]
    public partial class Bruger : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BrugerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrugerNavnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NavnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PointField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alias {
            get {
                return this.AliasField;
            }
            set {
                if ((object.ReferenceEquals(this.AliasField, value) != true)) {
                    this.AliasField = value;
                    this.RaisePropertyChanged("Alias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BrugerId {
            get {
                return this.BrugerIdField;
            }
            set {
                if ((this.BrugerIdField.Equals(value) != true)) {
                    this.BrugerIdField = value;
                    this.RaisePropertyChanged("BrugerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrugerNavn {
            get {
                return this.BrugerNavnField;
            }
            set {
                if ((object.ReferenceEquals(this.BrugerNavnField, value) != true)) {
                    this.BrugerNavnField = value;
                    this.RaisePropertyChanged("BrugerNavn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Navn {
            get {
                return this.NavnField;
            }
            set {
                if ((object.ReferenceEquals(this.NavnField, value) != true)) {
                    this.NavnField = value;
                    this.RaisePropertyChanged("Navn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Point {
            get {
                return this.PointField;
            }
            set {
                if ((this.PointField.Equals(value) != true)) {
                    this.PointField = value;
                    this.RaisePropertyChanged("Point");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DelKamp", Namespace="http://schemas.datacontract.org/2004/07/ModelLibrary.Kupon")]
    [System.SerializableAttribute()]
    public partial class DelKamp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DelKampIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KampIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AdminPanel.ServiceReference1.Kamp KampeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Valgt1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Valgt2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValgtXField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DelKampId {
            get {
                return this.DelKampIdField;
            }
            set {
                if ((this.DelKampIdField.Equals(value) != true)) {
                    this.DelKampIdField = value;
                    this.RaisePropertyChanged("DelKampId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KampId {
            get {
                return this.KampIdField;
            }
            set {
                if ((this.KampIdField.Equals(value) != true)) {
                    this.KampIdField = value;
                    this.RaisePropertyChanged("KampId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AdminPanel.ServiceReference1.Kamp Kampe {
            get {
                return this.KampeField;
            }
            set {
                if ((object.ReferenceEquals(this.KampeField, value) != true)) {
                    this.KampeField = value;
                    this.RaisePropertyChanged("Kampe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Valgt1 {
            get {
                return this.Valgt1Field;
            }
            set {
                if ((this.Valgt1Field.Equals(value) != true)) {
                    this.Valgt1Field = value;
                    this.RaisePropertyChanged("Valgt1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Valgt2 {
            get {
                return this.Valgt2Field;
            }
            set {
                if ((this.Valgt2Field.Equals(value) != true)) {
                    this.Valgt2Field = value;
                    this.RaisePropertyChanged("Valgt2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ValgtX {
            get {
                return this.ValgtXField;
            }
            set {
                if ((this.ValgtXField.Equals(value) != true)) {
                    this.ValgtXField = value;
                    this.RaisePropertyChanged("ValgtX");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kamp", Namespace="http://schemas.datacontract.org/2004/07/ModelLibrary.Kupon")]
    [System.SerializableAttribute()]
    public partial class Kamp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AflystField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoldVsHoldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KampIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime KampStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Odds1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double Odds2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double OddsXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Vundet1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Vundet2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool VundetXField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Aflyst {
            get {
                return this.AflystField;
            }
            set {
                if ((this.AflystField.Equals(value) != true)) {
                    this.AflystField = value;
                    this.RaisePropertyChanged("Aflyst");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoldVsHold {
            get {
                return this.HoldVsHoldField;
            }
            set {
                if ((object.ReferenceEquals(this.HoldVsHoldField, value) != true)) {
                    this.HoldVsHoldField = value;
                    this.RaisePropertyChanged("HoldVsHold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KampId {
            get {
                return this.KampIdField;
            }
            set {
                if ((this.KampIdField.Equals(value) != true)) {
                    this.KampIdField = value;
                    this.RaisePropertyChanged("KampId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime KampStart {
            get {
                return this.KampStartField;
            }
            set {
                if ((this.KampStartField.Equals(value) != true)) {
                    this.KampStartField = value;
                    this.RaisePropertyChanged("KampStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Odds1 {
            get {
                return this.Odds1Field;
            }
            set {
                if ((this.Odds1Field.Equals(value) != true)) {
                    this.Odds1Field = value;
                    this.RaisePropertyChanged("Odds1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Odds2 {
            get {
                return this.Odds2Field;
            }
            set {
                if ((this.Odds2Field.Equals(value) != true)) {
                    this.Odds2Field = value;
                    this.RaisePropertyChanged("Odds2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double OddsX {
            get {
                return this.OddsXField;
            }
            set {
                if ((this.OddsXField.Equals(value) != true)) {
                    this.OddsXField = value;
                    this.RaisePropertyChanged("OddsX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Vundet1 {
            get {
                return this.Vundet1Field;
            }
            set {
                if ((this.Vundet1Field.Equals(value) != true)) {
                    this.Vundet1Field = value;
                    this.RaisePropertyChanged("Vundet1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Vundet2 {
            get {
                return this.Vundet2Field;
            }
            set {
                if ((this.Vundet2Field.Equals(value) != true)) {
                    this.Vundet2Field = value;
                    this.RaisePropertyChanged("Vundet2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool VundetX {
            get {
                return this.VundetXField;
            }
            set {
                if ((this.VundetXField.Equals(value) != true)) {
                    this.VundetXField = value;
                    this.RaisePropertyChanged("VundetX");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServices")]
    public interface IServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/RedigerBeskrivelse", ReplyAction="http://tempuri.org/IServices/RedigerBeskrivelseResponse")]
        AdminPanel.ServiceReference1.SæsonBeskrivelse RedigerBeskrivelse(string beskrivelse, string start, string slut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/RedigerBeskrivelse", ReplyAction="http://tempuri.org/IServices/RedigerBeskrivelseResponse")]
        System.Threading.Tasks.Task<AdminPanel.ServiceReference1.SæsonBeskrivelse> RedigerBeskrivelseAsync(string beskrivelse, string start, string slut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/HentBeskrivelse", ReplyAction="http://tempuri.org/IServices/HentBeskrivelseResponse")]
        AdminPanel.ServiceReference1.SæsonBeskrivelse HentBeskrivelse();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/HentBeskrivelse", ReplyAction="http://tempuri.org/IServices/HentBeskrivelseResponse")]
        System.Threading.Tasks.Task<AdminPanel.ServiceReference1.SæsonBeskrivelse> HentBeskrivelseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/AfslutSæson", ReplyAction="http://tempuri.org/IServices/AfslutSæsonResponse")]
        void AfslutSæson();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/AfslutSæson", ReplyAction="http://tempuri.org/IServices/AfslutSæsonResponse")]
        System.Threading.Tasks.Task AfslutSæsonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/TilføjKamp", ReplyAction="http://tempuri.org/IServices/TilføjKampResponse")]
        AdminPanel.ServiceReference1.Kupon TilføjKamp(AdminPanel.ServiceReference1.Kupon kupon, AdminPanel.ServiceReference1.Kamp kamp, bool valgt1, bool valgtX, bool valgt2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/TilføjKamp", ReplyAction="http://tempuri.org/IServices/TilføjKampResponse")]
        System.Threading.Tasks.Task<AdminPanel.ServiceReference1.Kupon> TilføjKampAsync(AdminPanel.ServiceReference1.Kupon kupon, AdminPanel.ServiceReference1.Kamp kamp, bool valgt1, bool valgtX, bool valgt2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/FjernKamp", ReplyAction="http://tempuri.org/IServices/FjernKampResponse")]
        AdminPanel.ServiceReference1.Kupon FjernKamp(AdminPanel.ServiceReference1.Kamp kamp, AdminPanel.ServiceReference1.Kupon kupon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/FjernKamp", ReplyAction="http://tempuri.org/IServices/FjernKampResponse")]
        System.Threading.Tasks.Task<AdminPanel.ServiceReference1.Kupon> FjernKampAsync(AdminPanel.ServiceReference1.Kamp kamp, AdminPanel.ServiceReference1.Kupon kupon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/OddsUdregning", ReplyAction="http://tempuri.org/IServices/OddsUdregningResponse")]
        double OddsUdregning();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/OddsUdregning", ReplyAction="http://tempuri.org/IServices/OddsUdregningResponse")]
        System.Threading.Tasks.Task<double> OddsUdregningAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/MuligGevist", ReplyAction="http://tempuri.org/IServices/MuligGevistResponse")]
        double MuligGevist(AdminPanel.ServiceReference1.Kupon kupon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/MuligGevist", ReplyAction="http://tempuri.org/IServices/MuligGevistResponse")]
        System.Threading.Tasks.Task<double> MuligGevistAsync(AdminPanel.ServiceReference1.Kupon kupon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/BekræftKupon", ReplyAction="http://tempuri.org/IServices/BekræftKuponResponse")]
        bool BekræftKupon(AdminPanel.ServiceReference1.Kupon kupon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/BekræftKupon", ReplyAction="http://tempuri.org/IServices/BekræftKuponResponse")]
        System.Threading.Tasks.Task<bool> BekræftKuponAsync(AdminPanel.ServiceReference1.Kupon kupon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/FindKamp", ReplyAction="http://tempuri.org/IServices/FindKampResponse")]
        AdminPanel.ServiceReference1.Kamp FindKamp(int kampId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/FindKamp", ReplyAction="http://tempuri.org/IServices/FindKampResponse")]
        System.Threading.Tasks.Task<AdminPanel.ServiceReference1.Kamp> FindKampAsync(int kampId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetAlleKampe", ReplyAction="http://tempuri.org/IServices/GetAlleKampeResponse")]
        AdminPanel.ServiceReference1.Kamp[] GetAlleKampe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetAlleKampe", ReplyAction="http://tempuri.org/IServices/GetAlleKampeResponse")]
        System.Threading.Tasks.Task<AdminPanel.ServiceReference1.Kamp[]> GetAlleKampeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetAlleKuponer", ReplyAction="http://tempuri.org/IServices/GetAlleKuponerResponse")]
        AdminPanel.ServiceReference1.Kupon[] GetAlleKuponer(AdminPanel.ServiceReference1.Bruger bruger);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetAlleKuponer", ReplyAction="http://tempuri.org/IServices/GetAlleKuponerResponse")]
        System.Threading.Tasks.Task<AdminPanel.ServiceReference1.Kupon[]> GetAlleKuponerAsync(AdminPanel.ServiceReference1.Bruger bruger);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/NyKupon", ReplyAction="http://tempuri.org/IServices/NyKuponResponse")]
        AdminPanel.ServiceReference1.Kupon NyKupon();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/NyKupon", ReplyAction="http://tempuri.org/IServices/NyKuponResponse")]
        System.Threading.Tasks.Task<AdminPanel.ServiceReference1.Kupon> NyKuponAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetKampFromApi", ReplyAction="http://tempuri.org/IServices/GetKampFromApiResponse")]
        void GetKampFromApi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/GetKampFromApi", ReplyAction="http://tempuri.org/IServices/GetKampFromApiResponse")]
        System.Threading.Tasks.Task GetKampFromApiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/getIkkeSpilletKampe", ReplyAction="http://tempuri.org/IServices/getIkkeSpilletKampeResponse")]
        AdminPanel.ServiceReference1.Kamp[] getIkkeSpilletKampe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/getIkkeSpilletKampe", ReplyAction="http://tempuri.org/IServices/getIkkeSpilletKampeResponse")]
        System.Threading.Tasks.Task<AdminPanel.ServiceReference1.Kamp[]> getIkkeSpilletKampeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/getBruger", ReplyAction="http://tempuri.org/IServices/getBrugerResponse")]
        AdminPanel.ServiceReference1.Bruger getBruger(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/getBruger", ReplyAction="http://tempuri.org/IServices/getBrugerResponse")]
        System.Threading.Tasks.Task<AdminPanel.ServiceReference1.Bruger> getBrugerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/getBrugerEfterBrugernavn", ReplyAction="http://tempuri.org/IServices/getBrugerEfterBrugernavnResponse")]
        AdminPanel.ServiceReference1.Bruger getBrugerEfterBrugernavn(string bnavn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/getBrugerEfterBrugernavn", ReplyAction="http://tempuri.org/IServices/getBrugerEfterBrugernavnResponse")]
        System.Threading.Tasks.Task<AdminPanel.ServiceReference1.Bruger> getBrugerEfterBrugernavnAsync(string bnavn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/getBrugere", ReplyAction="http://tempuri.org/IServices/getBrugereResponse")]
        AdminPanel.ServiceReference1.Bruger[] getBrugere();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/getBrugere", ReplyAction="http://tempuri.org/IServices/getBrugereResponse")]
        System.Threading.Tasks.Task<AdminPanel.ServiceReference1.Bruger[]> getBrugereAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/opretBruger", ReplyAction="http://tempuri.org/IServices/opretBrugerResponse")]
        void opretBruger(AdminPanel.ServiceReference1.Bruger bruger);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/opretBruger", ReplyAction="http://tempuri.org/IServices/opretBrugerResponse")]
        System.Threading.Tasks.Task opretBrugerAsync(AdminPanel.ServiceReference1.Bruger bruger);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/opdaterBruger", ReplyAction="http://tempuri.org/IServices/opdaterBrugerResponse")]
        void opdaterBruger(AdminPanel.ServiceReference1.Bruger bruger);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/opdaterBruger", ReplyAction="http://tempuri.org/IServices/opdaterBrugerResponse")]
        System.Threading.Tasks.Task opdaterBrugerAsync(AdminPanel.ServiceReference1.Bruger bruger);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/sletBruger", ReplyAction="http://tempuri.org/IServices/sletBrugerResponse")]
        void sletBruger(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/sletBruger", ReplyAction="http://tempuri.org/IServices/sletBrugerResponse")]
        System.Threading.Tasks.Task sletBrugerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/logInd", ReplyAction="http://tempuri.org/IServices/logIndResponse")]
        AdminPanel.ServiceReference1.Bruger logInd(string bNavn, string pWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/logInd", ReplyAction="http://tempuri.org/IServices/logIndResponse")]
        System.Threading.Tasks.Task<AdminPanel.ServiceReference1.Bruger> logIndAsync(string bNavn, string pWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/getHighscores", ReplyAction="http://tempuri.org/IServices/getHighscoresResponse")]
        AdminPanel.ServiceReference1.Bruger[] getHighscores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/getHighscores", ReplyAction="http://tempuri.org/IServices/getHighscoresResponse")]
        System.Threading.Tasks.Task<AdminPanel.ServiceReference1.Bruger[]> getHighscoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/FeedBackReservedNames", ReplyAction="http://tempuri.org/IServices/FeedBackReservedNamesResponse")]
        string[] FeedBackReservedNames(string text, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/FeedBackReservedNames", ReplyAction="http://tempuri.org/IServices/FeedBackReservedNamesResponse")]
        System.Threading.Tasks.Task<string[]> FeedBackReservedNamesAsync(string text, int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicesChannel : AdminPanel.ServiceReference1.IServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicesClient : System.ServiceModel.ClientBase<AdminPanel.ServiceReference1.IServices>, AdminPanel.ServiceReference1.IServices {
        
        public ServicesClient() {
        }
        
        public ServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AdminPanel.ServiceReference1.SæsonBeskrivelse RedigerBeskrivelse(string beskrivelse, string start, string slut) {
            return base.Channel.RedigerBeskrivelse(beskrivelse, start, slut);
        }
        
        public System.Threading.Tasks.Task<AdminPanel.ServiceReference1.SæsonBeskrivelse> RedigerBeskrivelseAsync(string beskrivelse, string start, string slut) {
            return base.Channel.RedigerBeskrivelseAsync(beskrivelse, start, slut);
        }
        
        public AdminPanel.ServiceReference1.SæsonBeskrivelse HentBeskrivelse() {
            return base.Channel.HentBeskrivelse();
        }
        
        public System.Threading.Tasks.Task<AdminPanel.ServiceReference1.SæsonBeskrivelse> HentBeskrivelseAsync() {
            return base.Channel.HentBeskrivelseAsync();
        }
        
        public void AfslutSæson() {
            base.Channel.AfslutSæson();
        }
        
        public System.Threading.Tasks.Task AfslutSæsonAsync() {
            return base.Channel.AfslutSæsonAsync();
        }
        
        public AdminPanel.ServiceReference1.Kupon TilføjKamp(AdminPanel.ServiceReference1.Kupon kupon, AdminPanel.ServiceReference1.Kamp kamp, bool valgt1, bool valgtX, bool valgt2) {
            return base.Channel.TilføjKamp(kupon, kamp, valgt1, valgtX, valgt2);
        }
        
        public System.Threading.Tasks.Task<AdminPanel.ServiceReference1.Kupon> TilføjKampAsync(AdminPanel.ServiceReference1.Kupon kupon, AdminPanel.ServiceReference1.Kamp kamp, bool valgt1, bool valgtX, bool valgt2) {
            return base.Channel.TilføjKampAsync(kupon, kamp, valgt1, valgtX, valgt2);
        }
        
        public AdminPanel.ServiceReference1.Kupon FjernKamp(AdminPanel.ServiceReference1.Kamp kamp, AdminPanel.ServiceReference1.Kupon kupon) {
            return base.Channel.FjernKamp(kamp, kupon);
        }
        
        public System.Threading.Tasks.Task<AdminPanel.ServiceReference1.Kupon> FjernKampAsync(AdminPanel.ServiceReference1.Kamp kamp, AdminPanel.ServiceReference1.Kupon kupon) {
            return base.Channel.FjernKampAsync(kamp, kupon);
        }
        
        public double OddsUdregning() {
            return base.Channel.OddsUdregning();
        }
        
        public System.Threading.Tasks.Task<double> OddsUdregningAsync() {
            return base.Channel.OddsUdregningAsync();
        }
        
        public double MuligGevist(AdminPanel.ServiceReference1.Kupon kupon) {
            return base.Channel.MuligGevist(kupon);
        }
        
        public System.Threading.Tasks.Task<double> MuligGevistAsync(AdminPanel.ServiceReference1.Kupon kupon) {
            return base.Channel.MuligGevistAsync(kupon);
        }
        
        public bool BekræftKupon(AdminPanel.ServiceReference1.Kupon kupon) {
            return base.Channel.BekræftKupon(kupon);
        }
        
        public System.Threading.Tasks.Task<bool> BekræftKuponAsync(AdminPanel.ServiceReference1.Kupon kupon) {
            return base.Channel.BekræftKuponAsync(kupon);
        }
        
        public AdminPanel.ServiceReference1.Kamp FindKamp(int kampId) {
            return base.Channel.FindKamp(kampId);
        }
        
        public System.Threading.Tasks.Task<AdminPanel.ServiceReference1.Kamp> FindKampAsync(int kampId) {
            return base.Channel.FindKampAsync(kampId);
        }
        
        public AdminPanel.ServiceReference1.Kamp[] GetAlleKampe() {
            return base.Channel.GetAlleKampe();
        }
        
        public System.Threading.Tasks.Task<AdminPanel.ServiceReference1.Kamp[]> GetAlleKampeAsync() {
            return base.Channel.GetAlleKampeAsync();
        }
        
        public AdminPanel.ServiceReference1.Kupon[] GetAlleKuponer(AdminPanel.ServiceReference1.Bruger bruger) {
            return base.Channel.GetAlleKuponer(bruger);
        }
        
        public System.Threading.Tasks.Task<AdminPanel.ServiceReference1.Kupon[]> GetAlleKuponerAsync(AdminPanel.ServiceReference1.Bruger bruger) {
            return base.Channel.GetAlleKuponerAsync(bruger);
        }
        
        public AdminPanel.ServiceReference1.Kupon NyKupon() {
            return base.Channel.NyKupon();
        }
        
        public System.Threading.Tasks.Task<AdminPanel.ServiceReference1.Kupon> NyKuponAsync() {
            return base.Channel.NyKuponAsync();
        }
        
        public void GetKampFromApi() {
            base.Channel.GetKampFromApi();
        }
        
        public System.Threading.Tasks.Task GetKampFromApiAsync() {
            return base.Channel.GetKampFromApiAsync();
        }
        
        public AdminPanel.ServiceReference1.Kamp[] getIkkeSpilletKampe() {
            return base.Channel.getIkkeSpilletKampe();
        }
        
        public System.Threading.Tasks.Task<AdminPanel.ServiceReference1.Kamp[]> getIkkeSpilletKampeAsync() {
            return base.Channel.getIkkeSpilletKampeAsync();
        }
        
        public AdminPanel.ServiceReference1.Bruger getBruger(int id) {
            return base.Channel.getBruger(id);
        }
        
        public System.Threading.Tasks.Task<AdminPanel.ServiceReference1.Bruger> getBrugerAsync(int id) {
            return base.Channel.getBrugerAsync(id);
        }
        
        public AdminPanel.ServiceReference1.Bruger getBrugerEfterBrugernavn(string bnavn) {
            return base.Channel.getBrugerEfterBrugernavn(bnavn);
        }
        
        public System.Threading.Tasks.Task<AdminPanel.ServiceReference1.Bruger> getBrugerEfterBrugernavnAsync(string bnavn) {
            return base.Channel.getBrugerEfterBrugernavnAsync(bnavn);
        }
        
        public AdminPanel.ServiceReference1.Bruger[] getBrugere() {
            return base.Channel.getBrugere();
        }
        
        public System.Threading.Tasks.Task<AdminPanel.ServiceReference1.Bruger[]> getBrugereAsync() {
            return base.Channel.getBrugereAsync();
        }
        
        public void opretBruger(AdminPanel.ServiceReference1.Bruger bruger) {
            base.Channel.opretBruger(bruger);
        }
        
        public System.Threading.Tasks.Task opretBrugerAsync(AdminPanel.ServiceReference1.Bruger bruger) {
            return base.Channel.opretBrugerAsync(bruger);
        }
        
        public void opdaterBruger(AdminPanel.ServiceReference1.Bruger bruger) {
            base.Channel.opdaterBruger(bruger);
        }
        
        public System.Threading.Tasks.Task opdaterBrugerAsync(AdminPanel.ServiceReference1.Bruger bruger) {
            return base.Channel.opdaterBrugerAsync(bruger);
        }
        
        public void sletBruger(int id) {
            base.Channel.sletBruger(id);
        }
        
        public System.Threading.Tasks.Task sletBrugerAsync(int id) {
            return base.Channel.sletBrugerAsync(id);
        }
        
        public AdminPanel.ServiceReference1.Bruger logInd(string bNavn, string pWord) {
            return base.Channel.logInd(bNavn, pWord);
        }
        
        public System.Threading.Tasks.Task<AdminPanel.ServiceReference1.Bruger> logIndAsync(string bNavn, string pWord) {
            return base.Channel.logIndAsync(bNavn, pWord);
        }
        
        public AdminPanel.ServiceReference1.Bruger[] getHighscores() {
            return base.Channel.getHighscores();
        }
        
        public System.Threading.Tasks.Task<AdminPanel.ServiceReference1.Bruger[]> getHighscoresAsync() {
            return base.Channel.getHighscoresAsync();
        }
        
        public string[] FeedBackReservedNames(string text, int id) {
            return base.Channel.FeedBackReservedNames(text, id);
        }
        
        public System.Threading.Tasks.Task<string[]> FeedBackReservedNamesAsync(string text, int id) {
            return base.Channel.FeedBackReservedNamesAsync(text, id);
        }
    }
}
