//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCBetBud.BrugerServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bruger", Namespace="http://schemas.datacontract.org/2004/07/ModelLibrary.Bruger")]
    [System.SerializableAttribute()]
    public partial class Bruger : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BrugerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrugerNavnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NavnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alias {
            get {
                return this.AliasField;
            }
            set {
                if ((object.ReferenceEquals(this.AliasField, value) != true)) {
                    this.AliasField = value;
                    this.RaisePropertyChanged("Alias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BrugerId {
            get {
                return this.BrugerIdField;
            }
            set {
                if ((this.BrugerIdField.Equals(value) != true)) {
                    this.BrugerIdField = value;
                    this.RaisePropertyChanged("BrugerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrugerNavn {
            get {
                return this.BrugerNavnField;
            }
            set {
                if ((object.ReferenceEquals(this.BrugerNavnField, value) != true)) {
                    this.BrugerNavnField = value;
                    this.RaisePropertyChanged("BrugerNavn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Navn {
            get {
                return this.NavnField;
            }
            set {
                if ((object.ReferenceEquals(this.NavnField, value) != true)) {
                    this.NavnField = value;
                    this.RaisePropertyChanged("Navn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BrugerServiceReference.IBrugerService")]
    public interface IBrugerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrugerService/getBruger", ReplyAction="http://tempuri.org/IBrugerService/getBrugerResponse")]
        MVCBetBud.BrugerServiceReference.Bruger getBruger(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrugerService/getBruger", ReplyAction="http://tempuri.org/IBrugerService/getBrugerResponse")]
        System.Threading.Tasks.Task<MVCBetBud.BrugerServiceReference.Bruger> getBrugerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrugerService/getBrugere", ReplyAction="http://tempuri.org/IBrugerService/getBrugereResponse")]
        MVCBetBud.BrugerServiceReference.Bruger[] getBrugere();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrugerService/getBrugere", ReplyAction="http://tempuri.org/IBrugerService/getBrugereResponse")]
        System.Threading.Tasks.Task<MVCBetBud.BrugerServiceReference.Bruger[]> getBrugereAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrugerService/opretBruger", ReplyAction="http://tempuri.org/IBrugerService/opretBrugerResponse")]
        void opretBruger(MVCBetBud.BrugerServiceReference.Bruger bruger);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrugerService/opretBruger", ReplyAction="http://tempuri.org/IBrugerService/opretBrugerResponse")]
        System.Threading.Tasks.Task opretBrugerAsync(MVCBetBud.BrugerServiceReference.Bruger bruger);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrugerService/opdaterBruger", ReplyAction="http://tempuri.org/IBrugerService/opdaterBrugerResponse")]
        void opdaterBruger(MVCBetBud.BrugerServiceReference.Bruger bruger);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrugerService/opdaterBruger", ReplyAction="http://tempuri.org/IBrugerService/opdaterBrugerResponse")]
        System.Threading.Tasks.Task opdaterBrugerAsync(MVCBetBud.BrugerServiceReference.Bruger bruger);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrugerService/sletBruger", ReplyAction="http://tempuri.org/IBrugerService/sletBrugerResponse")]
        void sletBruger(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrugerService/sletBruger", ReplyAction="http://tempuri.org/IBrugerService/sletBrugerResponse")]
        System.Threading.Tasks.Task sletBrugerAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBrugerServiceChannel : MVCBetBud.BrugerServiceReference.IBrugerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BrugerServiceClient : System.ServiceModel.ClientBase<MVCBetBud.BrugerServiceReference.IBrugerService>, MVCBetBud.BrugerServiceReference.IBrugerService {
        
        public BrugerServiceClient() {
        }
        
        public BrugerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BrugerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrugerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrugerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MVCBetBud.BrugerServiceReference.Bruger getBruger(int id) {
            return base.Channel.getBruger(id);
        }
        
        public System.Threading.Tasks.Task<MVCBetBud.BrugerServiceReference.Bruger> getBrugerAsync(int id) {
            return base.Channel.getBrugerAsync(id);
        }
        
        public MVCBetBud.BrugerServiceReference.Bruger[] getBrugere() {
            return base.Channel.getBrugere();
        }
        
        public System.Threading.Tasks.Task<MVCBetBud.BrugerServiceReference.Bruger[]> getBrugereAsync() {
            return base.Channel.getBrugereAsync();
        }
        
        public void opretBruger(MVCBetBud.BrugerServiceReference.Bruger bruger) {
            base.Channel.opretBruger(bruger);
        }
        
        public System.Threading.Tasks.Task opretBrugerAsync(MVCBetBud.BrugerServiceReference.Bruger bruger) {
            return base.Channel.opretBrugerAsync(bruger);
        }
        
        public void opdaterBruger(MVCBetBud.BrugerServiceReference.Bruger bruger) {
            base.Channel.opdaterBruger(bruger);
        }
        
        public System.Threading.Tasks.Task opdaterBrugerAsync(MVCBetBud.BrugerServiceReference.Bruger bruger) {
            return base.Channel.opdaterBrugerAsync(bruger);
        }
        
        public void sletBruger(int id) {
            base.Channel.sletBruger(id);
        }
        
        public System.Threading.Tasks.Task sletBrugerAsync(int id) {
            return base.Channel.sletBrugerAsync(id);
        }
    }
}
