//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetBudTest.BrugerServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BrugerServiceRef.IBrugerService")]
    public interface IBrugerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrugerService/getBruger", ReplyAction="http://tempuri.org/IBrugerService/getBrugerResponse")]
        ModelLibrary.Bruger.Bruger getBruger(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrugerService/getBruger", ReplyAction="http://tempuri.org/IBrugerService/getBrugerResponse")]
        System.Threading.Tasks.Task<ModelLibrary.Bruger.Bruger> getBrugerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrugerService/getBrugerEfterBrugernavn", ReplyAction="http://tempuri.org/IBrugerService/getBrugerEfterBrugernavnResponse")]
        ModelLibrary.Bruger.Bruger getBrugerEfterBrugernavn(string bnavn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrugerService/getBrugerEfterBrugernavn", ReplyAction="http://tempuri.org/IBrugerService/getBrugerEfterBrugernavnResponse")]
        System.Threading.Tasks.Task<ModelLibrary.Bruger.Bruger> getBrugerEfterBrugernavnAsync(string bnavn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrugerService/getBrugere", ReplyAction="http://tempuri.org/IBrugerService/getBrugereResponse")]
        ModelLibrary.Bruger.Bruger[] getBrugere();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrugerService/getBrugere", ReplyAction="http://tempuri.org/IBrugerService/getBrugereResponse")]
        System.Threading.Tasks.Task<ModelLibrary.Bruger.Bruger[]> getBrugereAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrugerService/opretBruger", ReplyAction="http://tempuri.org/IBrugerService/opretBrugerResponse")]
        void opretBruger(ModelLibrary.Bruger.Bruger bruger);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrugerService/opretBruger", ReplyAction="http://tempuri.org/IBrugerService/opretBrugerResponse")]
        System.Threading.Tasks.Task opretBrugerAsync(ModelLibrary.Bruger.Bruger bruger);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrugerService/opdaterBruger", ReplyAction="http://tempuri.org/IBrugerService/opdaterBrugerResponse")]
        void opdaterBruger(ModelLibrary.Bruger.Bruger bruger);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrugerService/opdaterBruger", ReplyAction="http://tempuri.org/IBrugerService/opdaterBrugerResponse")]
        System.Threading.Tasks.Task opdaterBrugerAsync(ModelLibrary.Bruger.Bruger bruger);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrugerService/sletBruger", ReplyAction="http://tempuri.org/IBrugerService/sletBrugerResponse")]
        void sletBruger(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrugerService/sletBruger", ReplyAction="http://tempuri.org/IBrugerService/sletBrugerResponse")]
        System.Threading.Tasks.Task sletBrugerAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBrugerServiceChannel : BetBudTest.BrugerServiceRef.IBrugerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BrugerServiceClient : System.ServiceModel.ClientBase<BetBudTest.BrugerServiceRef.IBrugerService>, BetBudTest.BrugerServiceRef.IBrugerService {
        
        public BrugerServiceClient() {
        }
        
        public BrugerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BrugerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrugerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrugerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ModelLibrary.Bruger.Bruger getBruger(int id) {
            return base.Channel.getBruger(id);
        }
        
        public System.Threading.Tasks.Task<ModelLibrary.Bruger.Bruger> getBrugerAsync(int id) {
            return base.Channel.getBrugerAsync(id);
        }
        
        public ModelLibrary.Bruger.Bruger getBrugerEfterBrugernavn(string bnavn) {
            return base.Channel.getBrugerEfterBrugernavn(bnavn);
        }
        
        public System.Threading.Tasks.Task<ModelLibrary.Bruger.Bruger> getBrugerEfterBrugernavnAsync(string bnavn) {
            return base.Channel.getBrugerEfterBrugernavnAsync(bnavn);
        }
        
        public ModelLibrary.Bruger.Bruger[] getBrugere() {
            return base.Channel.getBrugere();
        }
        
        public System.Threading.Tasks.Task<ModelLibrary.Bruger.Bruger[]> getBrugereAsync() {
            return base.Channel.getBrugereAsync();
        }
        
        public void opretBruger(ModelLibrary.Bruger.Bruger bruger) {
            base.Channel.opretBruger(bruger);
        }
        
        public System.Threading.Tasks.Task opretBrugerAsync(ModelLibrary.Bruger.Bruger bruger) {
            return base.Channel.opretBrugerAsync(bruger);
        }
        
        public void opdaterBruger(ModelLibrary.Bruger.Bruger bruger) {
            base.Channel.opdaterBruger(bruger);
        }
        
        public System.Threading.Tasks.Task opdaterBrugerAsync(ModelLibrary.Bruger.Bruger bruger) {
            return base.Channel.opdaterBrugerAsync(bruger);
        }
        
        public void sletBruger(int id) {
            base.Channel.sletBruger(id);
        }
        
        public System.Threading.Tasks.Task sletBrugerAsync(int id) {
            return base.Channel.sletBrugerAsync(id);
        }
    }
}
